version: '3.0'

volumes:
  postgres_volume:

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: social_net
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_LOGIN=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=social_net
      - DB_TEST_PORT=5451
      - REFRESH_TOKEN_EXPIRES_IN=10080
      - ACCESS_TOKEN_EXPIRES_IN=15
      - ALGORITHM=HS256
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    networks:
      - mynetwork
  redis:
    image: redis:latest
    container_name: social_net_cache
    restart: always
    ports:
      - '6379:6379'
    networks:
      - mynetwork
  postgres:
    image: postgres:15.3-alpine
    container_name: social_net_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - '5455:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'social_net'
    networks:
      - mynetwork

networks:
  mynetwork: