version: '3.0'

volumes:
  postgres_volume:

services:
  redis:
    image: redis:latest
    container_name: social_net_cache
    restart: always
    ports:
      - '6379:6379'
  postgres:
    image: postgres:15.3-alpine
    container_name: social_net_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - '5450:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'social_net'