"""init

Revision ID: 45b499a98912
Revises: 
Create Date: 2023-07-06 03:28:33.171803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b499a98912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=35), nullable=False),
    sa.Column('last_name', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('modify_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['modify_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('dislike',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('reviewer', 'post_id')
    )
    op.create_table('like',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('reviewer', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('dislike')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
