"""rates

Revision ID: 53b2e68077ab
Revises: b3601aa1b2ca
Create Date: 2023-07-04 21:07:58.808117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b2e68077ab'
down_revision = 'b3601aa1b2ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislike',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['user_post.post_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('reviewer', 'post_id')
    )
    op.create_table('like',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['user_post.post_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('reviewer', 'post_id')
    )
    op.add_column('user_post', sa.Column('modify_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_post', 'user', ['modify_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('user_post', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_post', type_='foreignkey')
    op.drop_column('user_post', 'modify_id')
    op.drop_table('like')
    op.drop_table('dislike')
    # ### end Alembic commands ###
